name: Windows Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build (debug)
      run: cargo build --verbose
    - name: Build (release)
      run: cargo build --verbose --release
    - name: Archive binary (debug)
      uses: actions/upload-artifact@v3
      with:
        name: win-debug
        path: target/debug/vc_proxy_exports.exe
    - name: Archive binary (release)
      uses: actions/upload-artifact@v3
      with:
        name: win-release
        path: target/release/vc_proxy_exports.exe
